
name: Long (succeeds)

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          for OUTPUT in $(seq 1200); do
            echo "deez"
            sleep 3
          done
