name: Build and Deploy (succeeds)

on:
  push:
    branches:
      - "test"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: sleep 5 && echo hello && exit 0
 
